# $schema: http://json.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@dceba6193b3801e8342b1a5a6563300c0f7e437e

  verify-terraform:
    uses: harmelodic/workflows/.github/workflows/verify-terraform.yaml@dceba6193b3801e8342b1a5a6563300c0f7e437e
    with:
      directory: src
  release-terraform:
    needs: verify-terraform
    uses: harmelodic/workflows/.github/workflows/release-terraform.yaml@dceba6193b3801e8342b1a5a6563300c0f7e437e
    with:
      directory: src
      workspace: default
