# $schema: http://json.schemastore.org/github-workflow.json
name: pull-request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@dceba6193b3801e8342b1a5a6563300c0f7e437e

  verify-terraform:
    uses: harmelodic/workflows/.github/workflows/verify-terraform.yaml@dceba6193b3801e8342b1a5a6563300c0f7e437e
    with:
      directory: src
