# $schema: http://json.schemastore.org/github-workflow.json
name: pull-request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@9c9425790780e8e5a34289a409f080f2b413affd

  verify-terraform:
    uses: harmelodic/workflows/.github/workflows/verify-terraform.yaml@9c9425790780e8e5a34289a409f080f2b413affd
    with:
      directory: src
