# $schema: http://json.schemastore.org/github-workflow.json
name: pull-request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@d8a6bdec89321c9c3c7fcb448fa6b8394ddcdf95

  verify-terraform:
    uses: harmelodic/workflows/.github/workflows/verify-terraform.yaml@d8a6bdec89321c9c3c7fcb448fa6b8394ddcdf95
    with:
      directory: src
